name: Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y sbsigntool
          sudo snap install core core18
          sudo snap install --edge tpm2-simulator-chrisccoulson
    - name: Build
      run: go build -v
    - name: Test
      run: ./run-tests --with-mssim
    - name: Go vet
      run: go vet
